name: Run Frontrunner Bot

on:
  workflow_dispatch:
    inputs:
      gas_price_gwei:
        description: 'Gas price in Gwei'
        required: false
        default: '50'
      attempts:
        description: 'Number of attempts'
        required: false
        default: '10'
      interval:
        description: 'Interval between attempts (seconds)'
        required: false
        default: '5'

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Generate key pair
        run: python generate_key_pair.py > /dev/null 2>&1

      - name: Inject secret into settings.toml
        run: |
          sed -i '/^\[eoa\]/,/^$/d' settings.toml  # Remove existing [eoa] section
          echo "[eoa]" >> settings.toml
          echo "private_key = '${{ secrets.PRIVATE_KEY }}'" >> settings.toml

      - name: Run bot
        run: python play.py --gas_price_gwei ${{ github.event.inputs.gas_price_gwei }} --attempts ${{ github.event.inputs.attempts }} --interval ${{ github.event.inputs.interval }}
